### PR TITLE
Release s2ioperator v3.2.1

### PR DESCRIPTION
**Pull request by JohnNiang**
/cc @kubesphere-sigs/sig-devops

### CODE REVIEW

**Comment by JohnNiang** [comment]
Hi @kubesphere-sigs/sig-devops , I prefer to release s2ioperator to v3.3.0 instead of v3.2.1. Please see the important change: 
- https://github.com/kubesphere/s2ioperator/pull/163

What do you reckon?

**Comment by LinuxSuRen** [comment]
That PR already merged a long time. It's not in the plan of v3.3.0. Release v3.2.1 is ok enough.

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm

**Pull request merged**
